import LayoutWrapper from "../components/Landing/LayoutWrapper";
import "./globals.css";
import { ReduxProvider } from "./providers";

export const metadata = {
  title: "সব কিছু || অন্যরকম সব কিছু",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LayoutWrapper>
          <ReduxProvider>{children}</ReduxProvider>
        </LayoutWrapper>
      </body>
    </html>
  );
}
